### ISSUE TITLE
Process past WOEIP data

### ISSUE THREAD

**Issue by rsoden** [openoakland/woaq#18] opened 2018-06-15 20:26 UTC
We have some data here: 
https://drive.google.com/drive/u/0/folders/130VkLFcreQAJPaz0GnomeJ4aYCjQX7iI 

There will be more.

The code we from this PR should be used: https://github.com/openoakland/woaq/pull/4

**Comment by theecrit** [comment] 2018-09-28 19:12
@rsoden @TangoYankee  Cassandra showed me the staff computer where _most_ of this data appears to be stored, including a folder with a couple of hundred days' worth of data sets. I figured we could leave them as-is, and use them as source files when user testing as we go along. That way we can test with real data, in a real-world scenario. When we formally "launch," we can then do a bulk data upload with any remaining files.

This is also captured in Trello: https://trello.com/c/44C1knmE

**Comment by TangoYankee** [comment] 2018-09-29 15:02
@theecrit Anyway we could set up Google Drive Sync on the computer? It should be as simple as copy, paste, ... and then learn the Google Drive Interface

**Comment by theecrit** [comment] 2018-09-29 19:41
@TangoYankee The biggest hurdle is going to be computer literacy as a whole — understanding the difference between a desktop interface and a browser interface, for example. I'll clip some video to show examples of how CM troubleshoots when she isn't sure about something on the computer (hint: just clicking around the screen randomly, hoping the system responds). So whatever we build needs to be an _extremely_ simple UI, and preferably very few steps (though comfort level with a long checklist of steps was pretty good).

My instinct is that back-end complexity really isn't the issue (if it doesn't need hands-on maintenance), if the front-end UI is dead simple. But let's talk more about it once I've processed and shared the interview.

**Comment by TangoYankee** [comment] 2018-11-18 19:04
duplicate of [Trello Data Sets Card](https://trello.com/c/N3c6EY02/6-identify-where-the-data-sets-will-ultimately-live)

**Closed by TangoYankee** 2018-11-18 19:04 UTC
Labels: duplicate
